### ISSUE TITLE
v0.1.8 Mirrored Cortex: binascii.Error Odd-length string 

### ISSUE THREAD

**Issue by gleblanc1783** [vertexproject/synapse#1263]
**Describe the bug**
After manually editing the cell.guid file and ensuring they contain the same value, deploying multiple cortexes at the same time and one is started using the --mirror flag, the following error is shown:

```
mirror loop connected (tcp://foo:foo@synapse_master:27492/cortex
error in initCoreMirror loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse-0.1.8-py3.7.egg/synapse/cortex.py", line 792, in _initCoreMirror
    offs = await layr.getOffset(layr.iden)
  File "/usr/local/lib/python3.7/site-packages/synapse-0.1.8-py3.7.egg/synapse/lib/lmdblayer.py", line 517, in getOffset
    return self.offs.get(iden)
  File "/usr/local/lib/python3.7/site-packages/synapse-0.1.8-py3.7.egg/synapse/lib/slaboffs.py", line 13, in get
    buid = s_common.uhex(iden)
  File "/usr/local/lib/python3.7/site-packages/synapse-0.1.8-py3.7.egg/synapse/common.py", line 124, in uhex
    return binascii.unhexlify(text)
binascii.Error: Odd-length string
```

**To Reproduce**
1) Create 1 cortex with default options
2) Create another container and overwrite the cell.guid file with value of  cell.guid from step 1
3) Start cortex 2 with --mirror tcp://path/to/cortex/1

**Expected behavior**
The second cortex should spawn correctly and start to consume splices once they are available from the upstream cortex.

**Environment (please complete the following information):**
- OS: Mac OS 10.14.4 Mojave
- Docker: Docker version 18.09.2, build 6247962
- Python 3.7.3
- Synapse 0.1.8 image from Dockerhub

**Additional context**
It was suggested to change the /vertex/storage/cell.guid file to be the same on all Cortexes (both main and mirrored) so the deployment could get around the mirror having to be a backup.

**Comment by vEpiphyte** [comment]
@gleblanc1783 Can you include the hexdump  (xxd is fine) of your cell.guid files you modified  for the source and destination cortex?

**Comment by gleblanc1783** [comment]
Master:

`a884dabfc2b336a5c0717cd595a466a8  /vertex/storage/cell.guid
`
```
root@70ff0b334882:/# xxd /vertex/storage/cell.guid 
00000000: 3239 3461 6463 3338 3435 6430 3831 3464  294adc3845d0814d
00000010: 6466 3739 3532 3564 3230 6330 3238 3939  df79525d20c02899
00000020: 720a    
```

Mirror:

`a884dabfc2b336a5c0717cd595a466a8  /vertex/storage/cell.guid
`

```
root@7dd7760cfdaf:/# xxd /vertex/storage/cell.guid 
00000000: 3239 3461 6463 3338 3435 6430 3831 3464  294adc3845d0814d
00000010: 6466 3739 3532 3564 3230 6330 3238 3939  df79525d20c02899
00000020: 720a                                     r.

```

**Comment by vEpiphyte** [comment]
@gleblanc1783 The .guid files seem to have a extra `r` character on them. Can you remove them?

**Comment by gleblanc1783** [comment]
Yep - that helped. Not sure where the 'r' came from.

Now I'm seeing this, but it might just mean I need to give the mirror auth user special perms:

`synapse.exc.AuthDeny: AuthDeny: efile='cortex.py' eline=552 ename='syncLayerSplices' esrc="raise s_exc.AuthDeny(mesg=mesg, perm=('layer:sync', iden))" mesg='User must have permission layer:sync.294adc3845d0814ddf79525d20c02899.' perm=('layer:sync', '294adc3845d0814ddf79525d20c02899')`

**Comment by vEpiphyte** [comment]
correct - the user performing the sync must either have `layer:sync` permission or be a admin user.
