### ISSUE TITLE
[BUG] Cannot find default username and password for axon server

### ISSUE THREAD

**Issue by sunil3590** [vertexproject/synapse#1381]
**Describe the bug**
I started the Axon server and I am prompted for username/password when calling the "healthcheck" API. I cannot find anywhere in this repo, the default username and password

**Comment by invisig0th** [comment]
You can set the username / password via configuration options.  Check out the devops notes for the Cortex, the axon works the same way: https://synapse.docs.vertex.link/en/latest/synapse/devguides/devops_cortex.html
