### ISSUE TITLE
error msg when non-admin changes password

### ISSUE THREAD

**Issue by MalPunch3r** [vertexproject/synapse#1460]
When a non-admin user changes their password, it will change the password as expected, but the user gets this error.
AuthDeny: efile='cell.py' eline=42 ename='func' esrc='user=args[0].user.name)' mesg='User is not an admin.' user='testuser'

**To Reproduce**
python -m synapse.tools.cellauth cortex_test modify testuser --passwd testme2

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Synapse Version: v0.1.40
 - Python Version: 3.7.5
 - Output of `python -m pip freeze`
async-timeout==3.0.1
attrs==19.3.0
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
idna==2.8
lark-parser==0.7.8
lmdb==0.98
msgpack==0.6.2
multidict==4.7.0
pkg-resources==0.0.0
prompt-toolkit==2.0.10
pycparser==2.19
Pygments==2.3.1
pyOpenSSL==19.1.0
PyYAML==5.2
regex==2019.12.9
six==1.13.0
synapse==0.1.40
tornado==6.0.3
wcwidth==0.1.7
xxhash==1.4.3
yarl==1.4.2

**Comment by vEpiphyte** [comment]
@MalPunch3r Do you have a full traceback available?

**Comment by MalPunch3r** [comment]
No traceback is provided when it happens. You just get this message:
AuthDeny: efile='cell.py' eline=42 ename='func' esrc='user=args[0].user.name)' mesg='User is not an admin.' user='testuser'

**Comment by vEpiphyte** [comment]
The problem here is that the remote API ``getAuthInfo`` is an admin-only API, whereas the ``setPasswd``.  Relaxing ``getAuthInfo`` to allow a user to retrieve information associated with them would allow this to work and allow a user to find out what permissions/roles they have.

**Comment by vEpiphyte** [comment]
@MalPunch3r This is fixed in the latest release.

**Comment by MalPunch3r** [comment]
Cool - thanks!
