### ISSUE TITLE
Sqlite core fails to heed limit parameter for size functions

### ISSUE THREAD

**Issue by jnwatson** [vertexproject/synapse#167]
For example, a call like this:
```
core.getSizeBy('ge', 'foo', 42, limit=3)
```
may return a value greater than 3 due to the way sqlite works:
http://sqlite.1065341.n5.nabble.com/Limit-COUNT-td35980.html

Anyway, I might get to this. Just wanted to capture so it isn't forgotten.

**Comment by vEpiphyte** [comment]
@jnwatson Do you have a good example or test case for this?

**Comment by jnwatson** [comment]
Yep. Right in the unit test: https://github.com/vertexproject/synapse/blob/master/synapse/tests/test_cortex.py#L470

**Comment by vEpiphyte** [comment]
@jnwatson thanks!

**Comment by vEpiphyte** [comment]
current link https://github.com/vertexproject/synapse/blob/master/synapse/tests/test_cortex.py#L517

**Comment by vEpiphyte** [comment]
Preliminary work here https://github.com/vEpiphyte/synapse/tree/epiphyte_size_167

**Comment by vertexmc** [comment]
This is probably OBE by 010 work

**Comment by vertexmc** [comment]
Closing as OBE by 010.
