### ISSUE TITLE
[FEATURE] For awareness - Cortex XSOAR Integration

### ISSUE THREAD

**Issue by cmd-not-found** [vertexproject/synapse#1911]
## Cortex XSOAR Integration

This is for awareness only. 

I have developed a custom integration for Cortex XSOAR (Palo Alto's SOAR solution) and submitted it to their team for review. You're welcome to review, submit changes, comment on the PR, etc. You obviously know Synapse the best and this is just an open source contribution to connect a couple cool platforms. 

On the code itself, the platform relies on a few abstractions and some built-in functionality within the tool's python-based content. The platform separates the underlying application with the integration and automation content which they publish [here](https://github.com/demisto/content). The new integrations use a `BaseClient` class abstraction of the `requests` module to interact with 3rd-party APIs. So, to make it work for Synapse, I used the Synapse REST API and pinned it to the `demisto/aiohttp` docker image (more on that [here](https://github.com/demisto/dockerfiles) and the docker image [here](https://hub.docker.com/r/demisto/aiohttp)), so that we can use `aiohttp` on storm requests and read back the chunked data (although Cortex XSOAR really isn't suited for `async`). Their team will likely spend some time reviewing the new integration and have some suggestions for improving it.

#### Cortex XSOAR Pull Request
> **REF:** https://github.com/demisto/content/pull/9409

#### Cortex XSOAR Reference
> **REF:** https://xsoar.pan.dev/docs/welcome

> **Contributing Guidelines:** https://xsoar.pan.dev/docs/contributing/contributing

**Comment by invisig0th** [comment]
Thanks for making us aware!  This look great, we'll take a look!
