### ISSUE TITLE
add form that links file:bytes to file:path

### ISSUE THREAD

**Issue by vertexmc** [vertexproject/synapse#197]

**Comment by vEpiphyte** [comment]
@vertexmc is this still needed with the xref type?

**Comment by vertexmc** [comment]
@invisig0th said to hold off on this until optional fields in comp types are supported.

**Comment by vertexmc** [comment]
I think that `it:fs:file` solves this: https://github.com/vertexproject/synapse/blob/master/synapse/models/infotech.py#L150

**Comment by vertexmc** [comment]
`it:fs:file` links `file:bytes` to `file:path`
