### ISSUE TITLE
data model silently drops forms that lack a ptype

### ISSUE THREAD

**Issue by williballenthin** [vertexproject/synapse#219]
existing behavior:
it seems that in some cases, when a form declaration (added via `addDataModel`) does not have an associated ptype on its primary prop, the form does not get created. silently.

expected behavior: an exception is raised when the data model realizes there's a missing ptype.

i certainly owe you a test case before i expect this to be fixed. but wanted to note this for reference in the interim.

**Comment by invisig0th** [comment]
this may have come up as an edge case to my "if ptype is blank, assume the form name is the same as the type name" modification combined with the "delay forms that need types that dont exist yet" logic....  hrm.

**Comment by vEpiphyte** [comment]
@williballenthin Do you have a test case or example of this?

**Comment by vertexmc** [comment]
Closing as OBE by 010.
