### ISSUE TITLE
question: could csvtool work (in theory) with the REST api?

### ISSUE THREAD

**Issue by wesyoung** [vertexproject/synapse#2821]
skimming https://github.com/vertexproject/synapse/blob/master/synapse/tools/csvtool.py -- i'm wondering if csvtool could (in theory) be re-factored to support the REST API ? (ie: are there some specific things telepath provides the REST API does not? or is it simply that it was built for the lower level API and no one has contributed adaptation to interact with the REST API .. yet?)

not asking for work to be done; just getting a sense of how deep that hole might be..

(problem: I have REST api users who may want to use this and other tools, trying to determine future feasibility via the REST API vs telepath (certs, etc)).

**Comment by invisig0th** [comment]
Sorry for the extreeme lag :D  The logic in the csvtool relies on the ability to call storm and receive events back, so the streaming HTTP interface `/api/v1/storm` could be used to implement the same thing. Not technically REST because streaming output is not transactional, but def HTTP 👍
