### ISSUE TITLE
setprop() should take both full props and rel props

### ISSUE THREAD

**Issue by invisig0th** [vertexproject/synapse#288]
```
setprop(foo:bar:baz=10)
- or -
setprop(:baz=10)
```
rather than
```
setprop(baz=10)
```

**Comment by vEpiphyte** [comment]
@therealsilence This will involve a storm query syntax change (for docs purposes)

**Comment by vEpiphyte** [comment]
After discussion with @therealsilence and @invisig0th - going to make setprops ONLY take accept relative property arguments.
