### ISSUE TITLE
Storage layers should be capable of being revisioned - lmdb

### ISSUE THREAD

**Issue by vEpiphyte** [vertexproject/synapse#292]
Persistent storage layers should be capable of having schema changes applied to them. Use admin kv store to do revision tracking for migration purposes.

**Comment by invisig0th** [comment]
I propose we should expand the scope of this issue to include a full separation of the storage layer API from the Cortex?

**Comment by vEpiphyte** [comment]
We could do that - we'd just want to be crystal clear with what the storage layer API needs to implement.  This would be a significant change to how synapse.cores.common.Cortex (and current storage layers) are implemented, so we'd def need clear boundaries. 

We'd probably need an ref class stubbed out just for storage layer implementations to derive themselves from, in order to ensure that all the required functions are stubbed out and throw errors if not implemented.  This could easily lead to quick tests for new storage layers.

**Comment by vEpiphyte** [comment]
Closed in #301
