### ISSUE TITLE
AddNode() command fixes / clarification

### ISSUE THREAD

**Issue by therealsilence** [vertexproject/synapse#298]
Testing shows addnode() doesn't work "as expected". For example:

1. Can't create multiple nodes with addnode(). Per discussion this "should" work, although imho it's actually desirable that it DOESN'T (see below):
```
cli> ask addnode(inet:fqdn,a.colm,inet:fqdn,b.com)
oplog:
    addnode (took:1) {'sub': 0, 'mnem': 'addnode', 'excinfo': {'errfile': 'blah/blah/blah/synapse/synapse/lib/storm.py', 'errline': 965, 'errmsg': 'SyntaxError: ', 'errinfo': {}, 'err': 'SyntaxError'}, 'add': 0, 'took': 1}

options:
    limit = None
    uniq = 1

limits:
    lift = None
    time = None
    touch = None

(0 results)

```

2. Syntax to add secondary properties via addnode() unclear. Two issues:
a) Should specifying a secondary prop via addnode() ONLY work if the node does not already exist? That is, should you only be able to specify secondary prop=valu for NEW nodes (and otherwise need to use setprop())?
b) Should you be able to specify secondary props using either full or relative prop names?

Previous testing of a) seemed to imply secondary props could ONLY be set via addnode() for new nodes, though this has been hard to verify due to syntax issues with b).

Testing of b) seems to show that addnode() does not currently accept relative props:
```
cli> ask addnode(inet:fqdn,a.com,:created=2017-07-01)
inet:fqdn = a.com
(1 results)
cli> ask --props inet:fqdn=a.com
inet:fqdn = a.com
    :domain = com
    :host = a
    :sfx = False
    :zone = True
(1 results)
```
...and also that you can't set secondary props - even using full prop names - if the node already exists:
```
cli> ask addnode(inet:fqdn,a.com,inet:fqdn:created=2017-07-01)
inet:fqdn = a.com
(1 results)
cli> ask --props inet:fqdn=a.com
inet:fqdn = a.com
    :domain = com
    :host = a
    :sfx = False
    :zone = True
(1 results)
```

Desired behavior (from user perspective):
1. addnode() should only create one node at a time, e.g., addnode(form, value, prop=valu). If there is a need to create multiple nodes, you can use multiple addnode() commands in Storm or use the macro syntax [foo:bar=hurr foo:bar=derp].

2. addnode() should allow specification of one or more secondary prop=valu. prop should accept either full (foo:bar:baz) or relative (:baz) property names with respect to form, value. (Alternately, we simply need consistency as to:

- Whether Storm operators ("full" syntax) will accept full props, relative props, or both; and
- Whether macro syntax will accept full props, relative props or both.

I'm ok with limiting these (e.g. operators MUST take full props, macro syntax MUST take relative) but don't want inconsistency across operators (e.g., things like addnode() must take full props but setprop() must take relative).

3. addnode() will either create a new node, or return the specified node if it already exists. To avoid confusion, specifying a secondary property with addnode() should EITHER:

- created the node with the specified property (if the node doesn't exist) OR set the property to the specified value (if the node does exist). If this is problematic from a programming perspecptive, then:
- the user should get some type of error message to the effect that "node already exists, use setprop() to set secondary properties" (or "syntax error, node already exists" or whatever).

**Comment by vEpiphyte** [comment]
@therealsilence 
w/r/t property consistency - #288 / #296  will be moving the setprop() to accept either relative ":bar=10" or full "foo:bar=10" styles.  This will also apply to the macro syntax.

**Comment by therealsilence** [comment]
OBE based on refinement of data modification operators (e.g., addnonde(), setprop(), etc.)
