### ISSUE TITLE
CertDir: functions should only have one possible return type

### ISSUE THREAD

**Issue by vertexmc** [vertexproject/synapse#315]
Most of the functions in `CertDir` currently return a value or None.

- The functions which currently return a path or None should return a path or an empty string.
- The functions which currently return a certificate object or None should return the certificate or raise a Synapse exception.

**Comment by vertexmc** [comment]
These changes will affect `links/ssl.py`.

**Comment by vEpiphyte** [comment]
If we're cleaning up certdir, we should add module level docs showing the how-to-use it or easycert to spin up a CA and issue certs for infrastructure.

**Comment by invisig0th** [comment]
I pretty strongly prefer things returning None to raising "not found" exceptions because of the mess it creates for callers.  In many instances, "not found" is not what i would call an "exceptional circurmstance" so much as a conditional one.

**Comment by vertexmc** [comment]
@vEpiphyte - should I close this? (we were originally discussing this because of the doc standards)

**Comment by vertexmc** [comment]
Closing due to @invisig0th 's comment and https://github.com/vertexproject/synapse/issues/326

**Comment by vEpiphyte** [comment]
this rolls into #326
