### ISSUE TITLE
storage layer implementations should be separate from Cortex

### ISSUE THREAD

**Issue by vEpiphyte** [vertexproject/synapse#320]
from #292 - we should separate out the storage layers needed to implement a Cortex storage backing from the Cortex itself.  This would provide an interface that a storage layer needs to implement in order to work as the backing store for the Cortex class.

**Comment by jnwatson** [comment]
Need to revisit the stats delegation mechanism. IMHO, the default registered callbacks should include the getRowsByProp call (and removed from getStatByProp) so that the storage layer can simply override the _calcStatFoo func and not have to override getStatByProp.

**Comment by jnwatson** [comment]
The transaction stuff is kinda wishy washy. Sometimes queries under a Xact, sometimes not. Even just to document that would be good.

**Comment by vEpiphyte** [comment]
Notes from @invisig0th 

* the "row" level APIs/events are native to the Storage object, but wrappers are plumbed through the cortex
* A cortex has/creates a Storage instance and uses it as a strong-boundary API ( ie, Cortex logic is not Storage specific except for cases of modular features being present/missing )
* Tufo / Node level APIs events live at the cortex layer ( lol, obvs )
* Transactions are still created / maintained by the storage layer
* probably just stor.link(core) to bridge all storage events into the cortex bus.

**Comment by vEpiphyte** [comment]
From #350 - We'll need to identify tufo level apis which have possible storage layer optimizations, like getTufosByIdens which currently only has psql optimizations.

**Comment by vEpiphyte** [comment]
This is really a precursor to #319

**Comment by vertexmc** [comment]
@vEpiphyte - I have added a review to all three PRs.

**Comment by vEpiphyte** [comment]
this is closed in #362

**Comment by vEpiphyte** [comment]
@jnwatson Making separate stories to track Xact issues and possible stats changes.  Those both fell out of scope for this work.
