### ISSUE TITLE
plumb ssl support into webapp

### ISSUE THREAD

**Issue by vEpiphyte** [vertexproject/synapse#321]
provide a way to plumb ssl support into webapp, so that applications can be served by tornado which are ssl enabled.

**Comment by vertexmc** [comment]
I am currently working on this issue.

**Comment by vertexmc** [comment]
PR is up for this issue.

**Comment by vertexmc** [comment]
PR: https://github.com/vertexproject/synapse/pull/327
Future dmon work: https://github.com/vertexproject/synapse/issues/328
