### ISSUE TITLE
certdir - investigate password protecting pkcs12 output

### ISSUE THREAD

**Issue by vEpiphyte** [vertexproject/synapse#325]
pkcs12 files may be optionally encrypted; esp since they contain a user private key bundled with cert chain.  We should investigate if we can easily encrypt the pkcs12 object via a password, for protected cert generation/distribution.

**Comment by invisig0th** [comment]
This is currently fairly low priority.  Automation and "it just works" are pretty tough to achieve with this feature.  For "secure" key generation, we could also potentially make a "gen csr" option for user certs like the servers so the private key is generated by the client and never leaves a box.
