### ISSUE TITLE
Ingest subsystem does not apply tags to all relevant nodes

### ISSUE THREAD

**Issue by therealsilence** [vertexproject/synapse#334]
When requesting application of a tag based on a secondary property via an ingest file (ingest.json), the ingest subsystem does not apply the tag to all relevant nodes.

Specifically, file:bytes nodes can be created based on knowledge of an individual hash (md5, sha1, sha256, etc) in the absence of actual file bytes (results in a file:bytes node with a single secondary "hash" property) as well as based on the actual file bytes (in which case all hashes can be calculated and are present as secondary props).

Addtag() from the command line correctly applies a tag to all relevant nodes:
```
cli> ask file:bytes:sha256=027cc450ef5f8c5f653329641ec1fed91f694e0d229928963b30f6b0d7d3a745 [ #thesilence.testtag ]
file:bytes = 12eb3d4c3f2264b7056bcf6ebaf7e88d
    #thesilence.testtag (added 2017/07/11 17:08:32.798)
file:bytes = e090d1364d34aa8de6fe6db99e9855ac
    #thesilence.testtag (added 2017/07/11 17:08:33.074)
(2 results)
```

Requesting a tag addition from an ingest.json file applies the tag to one node only (seems to favor the node based on actual bytes vs a single-hash node):
Ingest file (snippet):
```
 "tags":[  "thesilence.mytest"  ],

"nodes":[
    ["file:bytes:sha256", [ "027cc450ef5f8c5f653329641ec1fed91f694e0d229928963b30f6b0d7d3a745" ]]
             ]
```
Storm query following ingest:
```
cli> ask file:bytes:sha256=027cc450ef5f8c5f653329641ec1fed91f694e0d229928963b30f6b0d7d3a745
file:bytes = 12eb3d4c3f2264b7056bcf6ebaf7e88d
    #thesilence.testtag (added 2017/07/11 17:08:32.798)
file:bytes = e090d1364d34aa8de6fe6db99e9855ac
    #thesilence.mytest (added 2017/07/11 17:11:09.352)
    #thesilence.testtag (added 2017/07/11 17:08:33.074)
```

**Comment by vEpiphyte** [comment]
In the ingest subsystem, the following code applies:

```            for form, vals in embed.get('nodes'):

                for valu in vals:
                    nodetags = list(tags)
                    nodeprops = dict(props)

                    info = {}
                    if type(valu) in (list, tuple):
                        valu, info = valu
                        nodetags.extend(info.get('tags', ()))
                        nodeprops.update(info.get('props', {}))

                    node = core.formTufoByProp(form, valu)

                    core.setTufoProps(node, **nodeprops)
                    core.addTufoTags(node, nodetags)```

Since we're only grabbing one node; if we have multiple nodes which could be lifted via core.formTufosbyProp(), we're only applying tags to the first node returned by the storage layer.

**Comment by vEpiphyte** [comment]
This may be a non-starter due to the problem found in #347

**Comment by vEpiphyte** [comment]
@therealsilence The problem described in this issue appears to have been the result of #347.  However, we still have the issue where secondary nodes created as a result of the primary node are NOT tagged by the ingest defined tag .  I'm not certain if there is a way to do that which does negatively impact on the performance of the ingest subsystem; or result in significant changes to other Cortex APIs.

**Comment by therealsilence** [comment]
Not sure we're describing the same problem. Secondary NODES should not be tagged - that is, if an ingest definition creates the inet:fqdn foo.woot.com and says tag that domain with #hurr.derp, the ingest subsystem should **NOT** automatically tag nodes derived from that inet:fqdn - that is, it should **not** also tag inet:fqdn woot.com or com.

However, if an ingest file effectively **specifies** a node based on a secondary prop=valu of the node, then **all** nodes that have that prop=valu should be tagged. So if I specify that file:bytes:md5 = *hash* should be tagged with #hurr.derp, then all file:bytes nodes with that prop=valu should receive the tag.

Right now this occurs most often (and most critically) with file:bytes nodes, but also applies to any comp node. The concern is fragmenting of analytical data (the same data is tagged in some places but not others) which both limits our ability to ask meaningful questions and makes it harder to identify where data should maybe be "folded" together.
 
I see it as the ingest equivalent of doing a lift + addtag - 

lift(file:bytes:md5, *hash* ) addtag( #hurr.derp )

Can ingest not do this? If it's a limitation in the subsystem we should clarify that.

**Comment by vEpiphyte** [comment]
synapse.lib.ingest removed in 010
