### ISSUE TITLE
Synapse dns model should support additional DNS record forms

### ISSUE THREAD

**Issue by therealsilence** [vertexproject/synapse#344]
Currently the Synapse DNS model (dns.py) supports mappings for the following DNS record types:

- DNS A record (inet:dns:a)
- DNS AAAA record (inet:dns:aaaa)
- DNS NS record (inet:dns:ns)

The following additional record types would be useful for modeling purposes (in order of most often encountered / most needed):

- DNS SOA record (inet:dns:soa) - note that an SOA record may return multiple fields per RFC1035, which may make it a candidate for comp type with optional fields. In public reporting, SOA is most often listed as an individual domain (inet:fqdn) or email (inet:email).
- DNS MX record (inet:dns:mx)
- DNS CNAME record (inet:dns:cname)
- DNS TXT record (inet:dns:txt)

This may also require updating the form for inet:dns:look to include additional data / record types from a one-time DNS lookup.

**Comment by vertexmc** [comment]
These forms already exist.
