### ISSUE TITLE
Modularize/layer to allow using subparts of synapse

### ISSUE THREAD

**Issue by jnwatson** [vertexproject/synapse#356]
It would be nice if I could use, for example, just the eventbus logic without including the dependencies the transitive closure over all the other parts of synapse.

Splitting out parts into separate subpackages would be one idea in this direction.

**Comment by vEpiphyte** [comment]
@jnwatson Is there a particular problem for you that this would solve?  As this stands, its a solution without a clear problem.

**Comment by jnwatson** [comment]
The above example is a good one. I'd like to just use the eventbus logic. Or just cortex without telepath or swarm.

**Comment by vEpiphyte** [comment]
The eventbus.py component in and of itself is relatively standalone as it is now - the raw EventBus class does not depend on very much (outside of python, just msgpack as part of the imports for 
synapse.common)

Removing the telepath requirements from the Cortex class has a non-trivial impact on Axon.  Is there a problem with the telepath importing for you that  related to #357 ?
