### ISSUE TITLE
Allow certain imports to fail and gracefully limit functionality

### ISSUE THREAD

**Issue by jnwatson** [vertexproject/synapse#357]
You don't actually need to have the py-lmdb package unless you're going to open a cortex with lmdb scheme.

You don't actually need cryptography or tornado if you're not using swarm or telepath. Conditionally including them, setting a global variable, and then checking that when the time comes to actually use it can enable parts of synapse to run in more places.

I have code that does this if anyone's interested.

**Comment by vertexmc** [comment]
@calebmadrigal proposed this a while back, but we decided against mainlining it.

**Comment by vEpiphyte** [comment]
https://github.com/vertexproject/synapse/pull/151

**Comment by vEpiphyte** [comment]
@jnwatson we've visited this before in #151 - is this a problem for you for some reason?  Requiring all the modules up front allows people to know they can reasonably use all of the components of synapse without headache.  We've had some discussion about it on slack as well (see archives related to 
#151).

If you have unusual deployment requirements where these libraries provide features that are not used by your deployment, one idea is that you could provide dummy packages which allow the import mechanisms to work and module attributes to resolve for any libraries which may be incidentally loaded but go unused.
