### ISSUE TITLE
pushfile test takes too long to run

### ISSUE THREAD

**Issue by vertexmc** [vertexproject/synapse#363]
`synapse.tests.test_tools_pushfile.TestPushFile.test_tools_pushfile` usually takes about 2/3 of the total time to run all of the tests on my machine.

**Comment by vEpiphyte** [comment]
adding needs triage since there isn't a clear RCA for why this is so slow at the moment.

**Comment by vEpiphyte** [comment]
Running this locally for me takes about 0.7 seconds. @vertexmc how long is it taking for you to run?

**Comment by vertexmc** [comment]
Sometimes it runs quickly, other times it takes over 1 minute. The test code seems pretty straightforward and sane though.

Ex:
```test_tools_pushfile (synapse.tests.test_tools_pushfile.TestPushFile) ... ok (47.4027s)```

**Comment by vertexmc** [comment]
That test almost always takes longer than 30s for me when I run all of the tests at once with the test script. It usually takes around 500ms when I run it individually.

**Comment by vEpiphyte** [comment]
This can be reproduced under heavy load.  Based on data collected with cProfile, most of the test time is spent doing the setup (cortex, axon) infrastructure that is used by the pushfile.main() function under test.

**Comment by vertexmc** [comment]
We discussed this a few days ago. The pushfile test is only taking a few seconds to run for me now, but the underlying issue still exists. Leaving issue open, but wanted to update that it wasn't still taking over 1min to run for me.

**Comment by vertexmc** [comment]
This is no longer an issue
