### ISSUE TITLE
Storm Operator for Filtering on Overlapping Sets

### ISSUE THREAD

**Issue by e2-ibm** [vertexproject/synapse#366]
Requesting a storm operator to filter based on what does or does not have an overlapping property. 

Use cases:

1. I have a set of inet:fqdn tufos. I want to be able to filter to return inet:fqdn tufos that are not linked to a registrant email address at all (there are no inet:fqdn that are also an inet:whois:regmail:fqdn). This will help to answer the question: of this list of domains, which have not been linked to an email registrant (and maybe from here, I need to triage/investigate these domains further)?

2. I have a set of inet:fqdn tufos. I want to be able to filter to return inet:fqdn tufos that are (or are not) linked to a supplied registrant email address foo@bar.baz (there are no inet:fqdn where inet:whois:regmail=(inet:fqdn,foo@bar.baz)). This will help to answer the question: of this list of domains, which are (or are not) registered by foo@bar.baz?

Future use cases:

1. I have a set of file:bytes. I want to filter to the set of file:bytes that are not linked to a yara rule. This set of files may need yara rules written for them.

2. I have a set of file:bytes. I want to filter to the set of file:bytes that are linked to a given yara rule.

**Comment by vEpiphyte** [comment]
This sounds like subquery support. Will loop back with @invisig0th about this.
