### ISSUE TITLE
regex macro filter eats query remainder

### ISSUE THREAD

**Issue by invisig0th** [vertexproject/synapse#367]
seems like string parsing after ~= needs to use the latest function in use by the rest of the macros that can be either whitespace *or* quote bounded.

**Comment by vEpiphyte** [comment]
noms :ramen:

**Comment by vEpiphyte** [comment]
reproduced in tests

**Comment by vEpiphyte** [comment]
Looking at this closer - all of our examples in unit tests are using double quotes to capture the regular expression.  We have one example in test_lib_storm which doesn't use quotes to delimit the regex value, but this only works because there is nothing AFTER the regex.

**Comment by vEpiphyte** [comment]
#370 opened to address this.
