### ISSUE TITLE
Unexpected results from refs() operator

### ISSUE THREAD

**Issue by therealsilence** [vertexproject/synapse#369]
refs() does not appear to correctly pivot to / from certain secondary properties. Specifically, refs() seems to fail on "deep" properties when attempting to do refs() from a set of file:txtref nodes:
```
file:txtref:xref:inet:ipv4
file:txtref:xref:inet:fqdn
```
etc.

See internal chat for details / example.

**Comment by invisig0th** [comment]
hrm.  yea.  this is likely caused by the fact that the props below :xref are not explicitly in the model.  seems like we need to make a special dark row to index this.

**Comment by e2-ibm** [comment]
Cannot pivot from txtref'd nodes to file:bytes node

> cli> ask --raw file:bytes=510ce6b579fed4cff92068dd099470cf
> [
>   [
>     "b27f3aacf96277c1ab90fd5bc6a17d67",
>     {
>       "#bhv": 1501096585599,
>       "#bhv.published": 1501096585599,
>       "#bhv.published.fireeye": 1501096585599,
>       "file:bytes": "510ce6b579fed4cff92068dd099470cf",
>       "file:bytes:md5": "cd790bf552fdb3e0563b5f60d4c7dcf7",
>       "file:bytes:mime": "??",
>       "file:bytes:name": "pivy-appendix.pdf",
>       "file:bytes:sha1": "0f1f4905addf483d71c42d0e59bd97f762559b80",
>       "file:bytes:sha256": "7bcb39a10be2b805632330df535c9225c887e6ebef500db91852bb04396cf3b8",
>       "file:bytes:sha512": "b7a17e9a563d59f7e23fc3d02373cc4a91e04509b47f7f90e9f6e6fbbdfbdf00c87e6bfe4a1b3c6a6ae87cc36e29b82590634d8d5a88a70add7ace19abd67b39",
>       "file:bytes:size": 2067982,
>       "tufo:form": "file:bytes"
>     }
>   ]
> ]
> (1 results)


> cli> ask --raw file:txtref:file=510ce6b579fed4cff92068dd099470cf
> [
>   [
>     "557cf83f113482b0d5d90ff677dea684",
>     {
>       "file:txtref": "f367f0d228e8d771cba5bba939b6461e",
>       "file:txtref:file": "510ce6b579fed4cff92068dd099470cf",
>       "file:txtref:xref:inet:passwd": "admin",
>       "file:txtref:xtype": "inet:passwd",
>       "tufo:form": "file:txtref"
>     }
>   ]
> ]
> (1 results)

> cli> ask --raw inet:passwd=admin refs()
> [
>   [
>     "5cf291a2b8c809f378de3a96ddfab826",
>     {
>       "inet:passwd": "admin",
>       "inet:passwd:md5": "21232f297a57a5a743894a0e4a801fc3",
>       "inet:passwd:sha1": "d033e22ae348aeb5660fc2140aec35850c4da997",
>       "inet:passwd:sha256": "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
>       "tufo:form": "inet:passwd"
>     }
>   ]
> ]
> (1 results)

**Comment by vEpiphyte** [comment]
This issue is no longer relevant as xref nodes are now pivotable via storm.
