### ISSUE TITLE
Storm "limit" parameter (or a limit() operator) should be usable as part of any query

### ISSUE THREAD

**Issue by therealsilence** [vertexproject/synapse#374]
"Limit" is an optional parameter used by a subset of Storm operators (e.g., lift, join, refs...?) to limit the resulting set of nodes to an arbitrary number. This is useful in cases such as when you want to retrieve a few "example" nodes to verify format or properties but don't want the full data set returned.

For analytical tasks, analysts should work with the full data set to avoid excluding relevant data. However, for things like troubleshooting ("why is my query not working?") or extremely large result sets where it would be helpful to display a subset of results. This means that "limit" (or an operator equivalent to limit) needs to be usable to filter / restrict the results of any arbitrary query. For example:
```
ask foo:bar +baz:faz -> hurr:derp limit(10)
```

**Comment by invisig0th** [comment]
mainlined.  will be in the next release.

**Comment by vEpiphyte** [comment]
Closed in #378
