### ISSUE TITLE
Inet model - url shortening / redirection services

### ISSUE THREAD

**Issue by vEpiphyte** [vertexproject/synapse#383]
Currently have no way to model "url A" redirects to "url B".  This is not a uncommon thing (bitly, googl, t.co, etc).

**Comment by e2-ibm** [comment]
+1

in addition to having the two URLs as secondary props would like time bounded secondary props as well

:seen:max
:seen:min

**Comment by vertexmc** [comment]
`inet:urlredir` exists to model this.
