### ISSUE TITLE
[ Question ] Query Routing Across Cortex Nodes: Non-Commercial Version

### ISSUE THREAD

**Issue by dfirence** [vertexproject/synapse#3947]
Hello -

for the non-commercial edition, is there a module or feature that routes a query to a Cortex node without explicitly declaring which Cortex node to use?

for instance, say I have 4 cortex nodes deployed on separate systems, how can I initiate a query and let Synapse handle the proper routing to the Cortex nodes?

**Comment by vEpiphyte** [comment]
Hello @dfirence 

Storm query pooling is available for deployments with Cortex mirrors. This allows Storm queries sent to the leader cortex to be routed to the query pool members.  The setup is documented here: https://synapse.docs.vertex.link/en/latest/synapse/deploymentguide.html#configure-a-storm-query-pool-optional

**Comment by dfirence** [comment]
@vEpiphyte - Thank you for the follow up.
