### ISSUE TITLE
Storm - token search capability

### ISSUE THREAD

**Issue by e2-ibm** [vertexproject/synapse#432]
Ability to search through certain properties.

Possible examples:
- ou:org:name:en
- file:path

**Comment by therealsilence** [comment]
Possibly a "by" handler for regex? lift by <prop> where <valu> contains <regex> ?

**Comment by invisig0th** [comment]
Regex syntax is capable of this for now.  Currently a full-text-indexing / tokenization is considered outside the scope for synapse.  :)
