### ISSUE TITLE
Axon: upload() implementation may save a file twice

### ISSUE THREAD

**Issue by vEpiphyte** [vertexproject/synapse#700]
The Axon ``upload()`` may save a file twice.  This results in a new buid being generated for the file.  It is possible that this may smash an existing buid+blob host combination, resulting in a blobstor having bytes that we have no way of knowing about.

No data is lost here, but extra disk space may be consumed.

**Comment by vEpiphyte** [comment]
Discussed this with @invisig0th - this is by design to support chunked uploads.  Docs will be updated to reflect this intended behavior.

**Comment by jnwatson** [comment]
Now OBE due to axon redesign.
